Upgrade go.mod files to Go 1.20
sigstore/sigstore pull request #1064
Opened 2023-03-31 04:25 UTC by clfs

#### Summary

Addresses https://github.com/sigstore/sigstore/issues/1063:

>Since PR https://github.com/sigstore/sigstore/pull/962, CI runs as Go 1.20: 
>
>https://github.com/sigstore/sigstore/blob/589100556a55096e80e6b3c0ca6028da6fb9adbb/.github/workflows/e2e_test.yml#L25
>
>It may make sense to upgrade the [go directive](https://go.dev/ref/mod#go-mod-file-go) in go.mod files to match:
>
>https://github.com/sigstore/sigstore/blob/589100556a55096e80e6b3c0ca6028da6fb9adbb/go.mod#L3

Go 1.18 was released ~a year ago; this PR brings Sigstore onto the latest stable version of Go. 

I tested this PR against `make` targets. E2E tests, linting, etc. succeed.

#### Release Note

Upgraded module go directives to Go 1.20.

#### Documentation

I think this only requires one update:

- https://docs.sigstore.dev/cosign/installation/#with-go-119 should read `With Go 1.20`

I checked by searching "1.17", "1.18", "1.19", and "1.20" in the [sigstore/docs]( https://github.com/sigstore/docs) repo.

2023-03-31 04:45 UTC, haydentherapper requested changes
Since we aren’t using any features of go 1.20, we had decided to keep it at 1.18

2023-03-31 05:22 UTC, clfs commented
@haydentherapper fair enough, thanks.

2023-03-31 07:25 UTC, cpanato commented on hack/tools/go.mod
> +go 1.20
i think here we can bump to go1.20 with no problem

2023-03-31 07:25 UTC, cpanato commented on test/fuzz/go.mod
> +go 1.20
here as well

2023-03-31 07:27 UTC, cpanato requested changes

2023-03-31 07:27 UTC, cpanato commented on go.mod
> +go 1.20
echoing @haydentherapper and this means the minimum required version to build this project

I would keep this as is for now and maybe we bump to go1.19 in a near future

2023-03-31 15:37 UTC, clfs commented
I reverted the top-level `go.mod` file to Go 1.18 per @cpanato's feedback.

2023-04-03 21:38 UTC, haydentherapper reviewed
I'd prefer we keep the same version of Go for the whole library, otherwise development gets tricky if you only have the older version

2023-04-05 09:07 UTC, cpanato commented
sgtm to me as well @haydentherapper 
@clfs can you sync all in the same? thanks!

2023-04-07 05:17 UTC, clfs commented
All `go.mod` files now sit on Go 1.18. Sorry for not checking beforehand; I could have made this smoother :)

2023-04-20 18:07 UTC, haydentherapper approved these changes
Sorry for not approving earlier, looks good, thanks!

2023-04-20 18:07 UTC, merged